"""Add image url to products

Revision ID: dc2787a73820
Revises: 74a8d1981ce6
Create Date: 2025-05-15 15:01:31.863588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2787a73820'
down_revision: Union[str, None] = '74a8d1981ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_column('products', 'imageUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('imageUrl', sa.VARCHAR(), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
